#!/usr/bin/env bash
# =============================================================================
# Seed Mock Services -- Ratify
# =============================================================================
# Generated by /make-it scaffold (fastapi-nextjs)
#
# Registers app users in mock-oidc, removes non-app users, and updates
# redirect URIs. Run after docker compose --profile dev up.
#
# Placeholders (replaced during /make-it build phase):
#   10090        - host port for mock-oidc (e.g., 10190)
#   3100         - host port for frontend (e.g., 3100)
#   ratify              - kebab-case app name
#   [ROLE_N_OIDC_SUB]       - OIDC subject for each role
#   [ROLE_N_EMAIL]          - email for each role
#   [ROLE_N_DISPLAY_NAME]   - display name for each role
#   [ADDITIONAL_MOCK_SEED]  - extra seeding for app-specific mock services
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
MOCK_OIDC_URL="http://localhost:10090"
CLIENT_ID="mock-oidc-client"
FRONTEND_URL="http://localhost:3100"
MAX_RETRIES=30

# App users (must match database seed oidc_subjects)
declare -a USER_SUBS=("mock-admin" "mock-manager" "mock-user" "mock-viewer")
declare -a USER_EMAILS=("admin@ratify.local" "manager@ratify.local" "engineer@ratify.local" "viewer@ratify.local")
declare -a USER_NAMES=("Admin User" "Sarah Chen" "Alex Rivera" "Jordan Kim")

echo ""
echo "======================================"
echo "  Mock Services Seed -- ratify"
echo "======================================"
echo ""

# ---------------------------------------------------------------------------
# Step 1: Wait for mock-oidc health
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[1/5] Waiting for mock-oidc to be healthy...${NC}"
RETRY_COUNT=0
until curl -sf "${MOCK_OIDC_URL}/health" > /dev/null 2>&1; do
    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
        echo -e "${RED}ERROR: mock-oidc did not become healthy after ${MAX_RETRIES} attempts${NC}"
        echo -e "${RED}Is mock-oidc running? Try: docker compose --profile dev up mock-oidc${NC}"
        exit 1
    fi
    echo "  Attempt ${RETRY_COUNT}/${MAX_RETRIES} -- waiting 2s..."
    sleep 2
done
echo -e "${GREEN}  mock-oidc is healthy${NC}"

# ---------------------------------------------------------------------------
# Step 2: Register app users
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[2/5] Registering app users in mock-oidc...${NC}"
for i in "${!USER_SUBS[@]}"; do
    SUB="${USER_SUBS[$i]}"
    EMAIL="${USER_EMAILS[$i]}"
    NAME="${USER_NAMES[$i]}"

    HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" \
        -X POST "${MOCK_OIDC_URL}/api/users" \
        -H "Content-Type: application/json" \
        -d "{\"sub\": \"${SUB}\", \"email\": \"${EMAIL}\", \"name\": \"${NAME}\"}" \
        2>/dev/null || echo "000")

    if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
        echo -e "${GREEN}  Registered: ${NAME} (${SUB})${NC}"
    elif [ "$HTTP_CODE" = "409" ]; then
        echo -e "${YELLOW}  Already exists: ${NAME} (${SUB})${NC}"
    else
        echo -e "${RED}  Failed to register ${NAME} (${SUB}) -- HTTP ${HTTP_CODE}${NC}"
    fi
done

# ---------------------------------------------------------------------------
# Step 3: Remove non-app users
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[3/5] Removing non-app users from mock-oidc...${NC}"

# Get current users from mock-oidc
CURRENT_USERS=$(curl -sf "${MOCK_OIDC_URL}/api/users" 2>/dev/null || echo "[]")

# Parse user subs using python3 (NOT jq -- not always installed)
CURRENT_SUBS=$(python3 -c "
import json, sys
users = json.loads('''${CURRENT_USERS}''')
for u in users:
    print(u['sub'])
" 2>/dev/null || echo "")

# Delete users not in app list
REMOVED=0
while IFS= read -r CURRENT_SUB; do
    [ -z "$CURRENT_SUB" ] && continue
    IS_APP_USER=false
    for APP_SUB in "${USER_SUBS[@]}"; do
        if [ "$CURRENT_SUB" = "$APP_SUB" ]; then
            IS_APP_USER=true
            break
        fi
    done
    if [ "$IS_APP_USER" = false ]; then
        HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" \
            -X DELETE "${MOCK_OIDC_URL}/api/users/${CURRENT_SUB}" \
            2>/dev/null || echo "000")
        if [ "$HTTP_CODE" = "200" ]; then
            echo -e "${GREEN}  Removed: ${CURRENT_SUB}${NC}"
            REMOVED=$((REMOVED + 1))
        else
            echo -e "${RED}  Failed to remove: ${CURRENT_SUB} -- HTTP ${HTTP_CODE}${NC}"
        fi
    fi
done <<< "$CURRENT_SUBS"

if [ "$REMOVED" -eq 0 ]; then
    echo -e "${GREEN}  No non-app users to remove${NC}"
fi

# ---------------------------------------------------------------------------
# Step 4: Update client redirect URIs
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[4/5] Updating client redirect URIs...${NC}"
CALLBACK_URI="${FRONTEND_URL}/api/auth/callback"
HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" \
    -X PUT "${MOCK_OIDC_URL}/api/clients/${CLIENT_ID}/redirect_uris" \
    -H "Content-Type: application/json" \
    -d "{\"redirect_uris\": [\"${CALLBACK_URI}\"]}" \
    2>/dev/null || echo "000")

if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}  Set redirect URI: ${CALLBACK_URI}${NC}"
else
    echo -e "${RED}  Failed to update redirect URIs -- HTTP ${HTTP_CODE}${NC}"
fi

# ---------------------------------------------------------------------------
# Step 5: Verify final user list
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[5/5] Verifying users in mock-oidc...${NC}"
FINAL_USERS=$(curl -sf "${MOCK_OIDC_URL}/api/users" 2>/dev/null || echo "[]")
python3 -c "
import json
users = json.loads('''${FINAL_USERS}''')
print(f'  Total users: {len(users)}')
for u in users:
    print(f\"  - {u['name']} ({u['sub']}) <{u['email']}>\")
"

# ---------------------------------------------------------------------------
# Step 6: Wait for mock-jira health
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[6/6] Waiting for mock-jira to be healthy...${NC}"
MOCK_JIRA_URL="http://localhost:8543"
RETRY_COUNT=0
until curl -sf "${MOCK_JIRA_URL}/health" > /dev/null 2>&1; do
    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
        echo -e "${YELLOW}WARNING: mock-jira did not become healthy -- Jira features will use fallback${NC}"
        break
    fi
    echo "  Attempt ${RETRY_COUNT}/${MAX_RETRIES} -- waiting 2s..."
    sleep 2
done
if [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; then
    echo -e "${GREEN}  mock-jira is healthy at ${MOCK_JIRA_URL}${NC}"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "======================================"
echo -e "${GREEN}  Mock services seeded successfully${NC}"
echo "======================================"
echo ""
echo "  mock-oidc:  ${MOCK_OIDC_URL}"
echo "  Login page: ${MOCK_OIDC_URL}/authorize?client_id=${CLIENT_ID}&redirect_uri=${CALLBACK_URI}&response_type=code&scope=openid"
echo ""
